global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: overwrite
  consul_sd_configs:
  - server: 'consul-node1:8500'
    services: ['prometheus_redis_exporter','prometheus_consul_exporter','prometheus_mongodb_exporter','prometheus_node_exporter','prometheus_rabbitmq_exporter','prometheus_mssql_exporter']