global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
    - 'rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'alertmanager'
  scrape_interval: 15s
  static_configs:
    - targets: ['localhost:9093']
- job_name: local-dev
  metrics_path: /prometheus
  consul_sd_configs:
  - server: '192.168.109.166:8500'
    services: []
    
  relabel_configs:
   - source_labels: [ '__meta_consul_service' ]
     target_label:  'service'
   - source_labels: [ '__meta_consul_health' ]
     target_label:  'health'
   - source_labels: [__meta_consul_tags]
     regex: '.*dev.*'     
     action: keep
   - regex: __meta_consul_service_metadata_(.+)
     action: labelmap
- job_name: local-test
  metrics_path: /prometheus
  consul_sd_configs:
  - server: '192.168.109.166:8500'
    services: []
  relabel_configs:
   - source_labels: [ '__meta_consul_service' ]
     target_label:  'service'
   - source_labels: [ '__meta_consul_health' ]
     target_label:  'health'
   - source_labels: [__meta_consul_tags]
     regex: '.*test.*'     
     action: keep
   - regex: __meta_consul_service_metadata_(.+)
     action: labelmap
- job_name: local-sbx
  metrics_path: /prometheus
  consul_sd_configs:
  - server: '192.168.109.166:8500'
    services: []
  relabel_configs:
   - source_labels: [ '__meta_consul_service' ]
     target_label:  'service'
   - source_labels: [ '__meta_consul_health' ]
     target_label:  'health'
   - source_labels: [__meta_consul_tags]
     regex: '.*sbx.*'     
     action: keep
   - regex: __meta_consul_service_metadata_(.+)
     action: labelmap
- job_name: local-qas
  metrics_path: /prometheus
  consul_sd_configs:
  - server: '192.168.109.166:8500'
    services: []
  relabel_configs:
   - source_labels: [ '__meta_consul_service' ]
     target_label:  'service'
   - source_labels: [ '__meta_consul_health' ]
     target_label:  'health'
   - source_labels: [__meta_consul_tags]
     regex: '.*qas.*'     
     action: keep
   - regex: __meta_consul_service_metadata_(.+)
     action: labelmap
