{
 "title": "RDS Detail",
 "description": "Alibaba Cloud RDS Dashboard",
 "tags": [
  "Prometheus",
  "ALIYUN",
  "RDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(aliyun_meta_rds_info, DBInstanceDescription)"
   },
   {
    "name": "instanceId",
    "query": "label_values(aliyun_meta_rds_info{DBInstanceDescription=\"$hostname\"}, DBInstanceId)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aliyun_meta_rds_info{DBInstanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_MySQL_NetworkInNew{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") \n",
     "legendFormat": "In"
    },
    {
     "expr": "(-aliyun_acs_rds_dashboard_MySQL_NetworkOutNew{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_MySQL_ActiveSessions{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")\n\n"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n(aliyun_acs_rds_dashboard_CpuUsage{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")\n\n"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n\n(aliyun_acs_rds_dashboard_MemoryUsage{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")\n\n",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "IOPS Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n\n\n(aliyun_acs_rds_dashboard_IOPSUsage{instanceId=~\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n\n(aliyun_acs_rds_dashboard_ConnectionUsage{instanceId=~\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n\n(aliyun_acs_rds_dashboard_DiskUsage{instanceId=~\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_rds_info{},\"instanceId\",\"$1\",\"DBInstanceId\",\"(.*)\")",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Engine Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  }
 ]
}