{
 "title": "ECS Overview",
 "tags": [
  "ALIYUN",
  "Prometheus",
  "ECS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h" },
   { "name": "threshold", "query": "0,50,60,70,80,90" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"ecs.*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "P95 CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_CPUUtilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_load_5m)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "P95 Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "quantile(0.95, aliyun_acs_ecs_dashboard_memory_usedutilization)",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_CPUUtilization{}[$interval])) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\") >=$threshold"
    },
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_memory_usedutilization{}[$interval])) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")   >=$threshold"
    },
    {
     "expr": "(avg_over_time(aliyun_acs_ecs_dashboard_net_tcpconnection{state=\"TCP_TOTAL\"}[$interval])) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")"
    }
   ]
  },
  {
   "title": "ECS磁盘使用情况",
   "type": "table",
   "gridPos": { "h": 21, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_diskusage_utilization{}) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")>$threshold"
    }
   ]
  },
  {
   "title": "阿里云ECS磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_diskusage_utilization{}) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")>=90",
     "legendFormat": "{{InstanceName}} {{device}}"
    }
   ]
  },
  {
   "title": "阿里云ECS内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_memory_usedutilization{}) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")>=80",
     "legendFormat": "{{RegionId}}:{{InstanceName}}"
    }
   ]
  },
  {
   "title": "阿里云ECS CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_CPUUtilization{}) * on (instanceId,instance) group_left(HostName,InnerIpAddress,PublicIpAddress,RegionId,InstanceName,OSType,OSName,CreationTime,ExpiredTime,InternetChargeType,Cpu,Memory,userId) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")>=50",
     "legendFormat": "{{RegionId}}:{{InstanceName}}"
    }
   ]
  }
 ]
}