{
 "title": "SLB Detail",
 "tags": [
  "Prometheus",
  "ALIYUN",
  "SLB"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "query": "label_values(aliyun_acs_slb_dashboard_MaxConnection, vip)"
   },
   {
    "name": "port",
    "query": "label_values(aliyun_acs_slb_dashboard_MaxConnection{vip=\"$vip\"}, port)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_TrafficRXNew{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_TrafficTXNew{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "RT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(aliyun_acs_slb_dashboard_Rt{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "SLB"
    },
    {
     "expr": "avg(aliyun_acs_slb_dashboard_UpstreamRt{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_Qps{vip=\"$vip\",port=~\"$port\"})"
    }
   ]
  },
  {
   "title": "Error Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode4xx{vip=\"$vip\",port=~\"$port\"}) / sum(aliyun_acs_slb_dashboard_Qps{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode5xx{vip=\"$vip\",port=~\"$port\"}) / sum(aliyun_acs_slb_dashboard_Qps{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "StatusCode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode2xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode3xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode4xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_StatusCode5xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Traffic Drop Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_DropTrafficTX{vip=\"$vip\",port=~\"$port\"}) / sum(aliyun_acs_slb_dashboard_TrafficTXNew{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_DropTrafficRX{vip=\"$vip\",port=~\"$port\"}) / sum(aliyun_acs_slb_dashboard_TrafficRXNew{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "4XX"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(aliyun_acs_slb_dashboard_ActiveConnection{vip=\"$vip\",port=~\"$port\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(aliyun_acs_slb_dashboard_MaxConnection{vip=\"$vip\",port=~\"$port\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Drop Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(aliyun_acs_slb_dashboard_DropConnection{vip=\"$vip\",port=~\"$port\"})",
       "legendFormat": "Dropped"
      }
     ]
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Upstream Servers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_HeathyServerCount{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_UnhealthyServerCount{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Upstream Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_slb_dashboard_UpstreamCode4xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(aliyun_acs_slb_dashboard_UpstreamCode5xx{vip=\"$vip\",port=~\"$port\"})",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}