{
 "title": "RDS Overview",
 "tags": [
  "Prometheus",
  "ALIYUN",
  "RDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "threshold", "query": "0,50,60,70,80,90" }
  ]
 },
 "panels": [
  {
   "title": "Running Instance Count",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(aliyun_meta_rds_info{DBInstanceStatus=\"Running\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=~\"rds.*\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Overall Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_rds_dashboard_MySQL_NetworkOutNew)"
    }
   ]
  },
  {
   "title": "Overall Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(aliyun_acs_rds_dashboard_MySQL_ActiveSessions)"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(avg_over_time(aliyun_acs_rds_dashboard_CpuUsage{}[$interval])) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "(avg_over_time(aliyun_acs_rds_dashboard_MemoryUsage{}[$interval])) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "(avg_over_time(aliyun_acs_rds_dashboard_IOPSUsage{}[$interval])) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    },
    {
     "expr": "(avg_over_time(aliyun_acs_rds_dashboard_DiskUsage{}[$interval])) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\") >= $threshold"
    }
   ]
  },
  {
   "title": "阿里云RDS CPU使用率 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_CpuUsage{}) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\")>=50",
     "legendFormat": "{{RegionId}}:{{DBInstanceDescription}}"
    }
   ]
  },
  {
   "title": "阿里云RDS 磁盘使用率 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_DiskUsage{}) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\")>=50",
     "legendFormat": "{{RegionId}}:{{DBInstanceDescription}}"
    }
   ]
  },
  {
   "title": "阿里云RDS 内存使用率 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_MemoryUsage{}) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\")>=50",
     "legendFormat": "{{RegionId}}:{{DBInstanceDescription}}"
    }
   ]
  },
  {
   "title": "阿里云RDS 连接数使用率 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_ConnectionUsage{}) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\")>=20",
     "legendFormat": "{{RegionId}}:{{DBInstanceDescription}}"
    }
   ]
  },
  {
   "title": "阿里云RDS IOPS使用率 ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_rds_dashboard_IOPSUsage{}) * on (instanceId,instance) group_left(InstanceId,DBInstanceDescription,DBInstanceStatus,RegionId) \nlabel_replace(aliyun_meta_rds_info, \"instanceId\", \"$1\", \"DBInstanceId\", \"(.*)\")>=20",
     "legendFormat": "{{RegionId}}:{{DBInstanceDescription}}"
    }
   ]
  }
 ]
}