{
 "title": "ECS Detail",
 "description": "Alibaba Cloud ECS Instance Dashboard",
 "tags": [
  "ALIYUN",
  "Prometheus",
  "ECS"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(aliyun_meta_ecs_info, HostName)"
   },
   {
    "name": "instanceId",
    "query": "label_values(aliyun_meta_ecs_info{HostName=\"$hostname\"}, InstanceId)"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aliyun_meta_ecs_info{InstanceId=\"$instanceId\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n(aliyun_acs_ecs_dashboard_CPUUtilization{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_memory_usedutilization{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Disk Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\n(aliyun_acs_ecs_dashboard_memory_usedutilization{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "inode Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_fs_inodeutilization{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "LoadAvg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_load_1m{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "1m"
    },
    {
     "expr": "\n(aliyun_acs_ecs_dashboard_load_5m{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "5m"
    },
    {
     "expr": "\n(aliyun_acs_ecs_dashboard_load_15m{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "\"Actual Used\" do not include cache/buffer",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_memory_totalspace{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Total"
    },
    {
     "expr": "(aliyun_acs_ecs_dashboard_memory_usedspace{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Used"
    },
    {
     "expr": "(aliyun_acs_ecs_dashboard_memory_actualusedspace{instanceId=\"$instanceId\"}) * on (instanceId,instance) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Actual Used"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_net_tcpconnection{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Intranet Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_IntranetIn{instanceId=\"$instanceId\"})",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Internet Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetIn{instanceId=\"$instanceId\"})",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(aliyun_acs_ecs_dashboard_InternetOut{instanceId=\"$instanceId\"})",
     "legendFormat": "Tx"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_DiskReadBPS{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Read"
    },
    {
     "expr": "(aliyun_acs_ecs_dashboard_DiskWriteBPS{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "(aliyun_acs_ecs_dashboard_DiskReadIOPS{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Read"
    },
    {
     "expr": "(aliyun_acs_ecs_dashboard_DiskWriteIOPS{instanceId=\"$instanceId\"}) * on (instanceId,instance)   group_left(HostName) \nlabel_replace(aliyun_meta_ecs_info{},\"instanceId\",\"$1\",\"InstanceId\",\"(.*)\")",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}